spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/mydb
    username: makingdevs
    password: makingdevs
  jpa:
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImproveNamingStrategy